export const tableData = [
  {
    name: 'Kantipudi Samyuktha',
    regNo: '18K61A0556',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kanuri Navya Sri',
    regNo: '18K61A0557',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'K Venkata Sai Prasadu',
    regNo: '18K61A0558',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Karuturi Geetha Madhavi',
    regNo: '18K61A0559',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kasagani Usha Sree',
    regNo: '18K61A0560',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kasani Durga Navya Sri',
    regNo: '18K61A0561',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kasanneni Yaswanth Sai',
    regNo: '18K61A0562',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Katiki Yasaswini',
    regNo: '18K61A0563',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Katta Bujji',
    regNo: '18K61A0564',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kesiraju Venkat',
    regNo: '18K61A0565',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kirla Ajay Durga',
    regNo: '18K61A0566',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Koduri Navya',
    regNo: '18K61A0567',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Koka Pavani Sai Lakshmi',
    regNo: '18K61A0568',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Konakalla Durga Pavani',
    regNo: '18K61A0569',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Konijetiadityakumar',
    regNo: '18K61A0570',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Koppula Durga Devi',
    regNo: '18K61A0571',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kota Hemanth Kumar',
    regNo: '18K61A0572',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kothuri Sindhu',
    regNo: '18K61A0573',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kotipi Mounica Reddy',
    regNo: '18K61A0574',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kotti Lakshmi Poojitha',
    regNo: '18K61A0575',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Lakamsani Lakshmi Srihitha',
    regNo: '18K61A0576',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Maddipati Durga Devi',
    regNo: '18K61A0577',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Maddipati Harika',
    regNo: '18K61A0578',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Maganti Sai Sudheer',
    regNo: '18K61A0579',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Malladi Sri Lakshmi',
    regNo: '18K61A0580',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mandagadla Vamsi Krishna',
    regNo: '18K61A0581',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Manday Sudheer',
    regNo: '18K61A0582',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mangam Mahesh',
    regNo: '18K61A0583',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Manne Jyothi',
    regNo: '18K61A0584',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'MedapatiAmrutha Reddy',
    regNo: '18K61A0585',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Medapati Sivani',
    regNo: '18K61A0586',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Meka Vijaya Sunil',
    regNo: '18K61A0587',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Modepalli Lakshmi Vasanthi',
    regNo: '18K61A0588',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mohammad Nafisa Fathima',
    regNo: '18K61A0589',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mohammad Sabiya Khanam',
    regNo: '18K61A0590',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mudunuri Prasanthi',
    regNo: '18K61A0591',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Muppiri Karteek',
    regNo: '18K61A0592',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Mygapula Aneetha',
    regNo: '18K61A0593',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nadella Renuka',
    regNo: '18K61A0594',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nadiminti Vyshnu',
    regNo: '18K61A0595',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nagaraju Haarika',
    regNo: '18K61A0596',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nakka Sushma',
    regNo: '18K61A0597',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nandigam Srinivasu',
    regNo: '18K61A0598',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nekkanti Likhitha Devi',
    regNo: '18K61A0599',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'NS Kanaka Durga Mahesh',
    regNo: '18K61A05A0',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nukalapu Mounika',
    regNo: '18K61A05A1',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nune Jahna Tejaswi',
    regNo: '18K61A05A2',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nune Rashmika',
    regNo: '18K61A05A3',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nunna Ramya',
    regNo: '18K61A05A4',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nyshadham Sri Ram Mohan',
    regNo: '18K61A05A5',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'PachipalaVamsi',
    regNo: '18K61A05A6',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Padebettu Nikhitha',
    regNo: '18K61A05A7',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Palakodeti B N M R Dora Prasad',
    regNo: '18K61A05A8',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Palakodeti Kavya',
    regNo: '18K61A05A9',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Pampana Usha Anusha',
    regNo: '18K61A05B0',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'B Phanindra Kumar',
    regNo: '19K65A0509',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Eedara Manikanta',
    regNo: '19K65A0510',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Kayala Eswara Sai Srinivas',
    regNo: '19K65A0511',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nakka Eswara Sai Jagadeesh',
    regNo: '19K65A0512',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Nunna Krishna Vamsi',
    regNo: '19K65A0513',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Putta Vinay Sai Teja',
    regNo: '19K65A0514',
    isChecked: true,
    status: 'Present',
  },
  {
    name: 'Dasari Swathi',
    regNo: '19K65A0515',
    isChecked: true,
    status: 'Present',
  },
]
